version: '2'
services:
  app:
    build: app
    ports:
      - "8080"
  e2e-tests:
    build: e2e
    volumes:
      - "./e2e/test:/app/test"
      - "./e2e/screenshots:/app/screenshots"
    links:
      - app
      - selenium-chrome
  selenium-chrome:
    image: selenium/standalone-chrome:3.4.0
    ports:
      - "4444"
